# Generated by pip2nix 0.8.0.dev1, then tweaked
# See https://github.com/nix-community/pip2nix
self: super:
let
  pkgs = self;
  fetchurl = pkgs.fetchurl;
in
{
  python3Packages = {

    # "bottle" = super.buildPythonPackage rec {
    #   pname = "bottle";
    #   version = "0.12.19";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/bf/44/aeafdd6ca05a8e1c3f91eeeb272a202d5cb1b3b23730a5ca686a81c48d24/bottle-0.12.19-py3-none-any.whl";
    #     sha256 = "0gbjd80lbws15inianwb2mmcwsfafbdr0af02fc6yh5ax57s7f7n";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [ ];
    # };
    # "certifi" = super.buildPythonPackage rec {
    #   pname = "certifi";
    #   version = "2020.12.5";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl";
    #     sha256 = "0c4qsp7q10hhiryvl6dyxsfh9r1mpja8sfkzri2bvf9kkvxp96ki";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [ ];
    # };
    # # "cffi" = super.buildPythonPackage rec {
    # #   pname = "cffi";
    # #   version = "1.14.4";
    # #   src = fetchurl {
    # #     url = "https://files.pythonhosted.org/packages/66/6a/98e023b3d11537a5521902ac6b50db470c826c682be6a8c661549cb7717a/cffi-1.14.4.tar.gz";
    # #     sha256 = "0v080s7vlrjz9z823x2yh36yc8drwpvvir6w8wfkkzd7k2z5qihs";
    # #   };
    # #   format = "setuptools";
    # #   doCheck = false;
    # #   buildInputs = [ ];
    # #   checkInputs = [ ];
    # #   nativeBuildInputs = [ ];
    # #   propagatedBuildInputs = [
    # #     self."pycparser"
    # #   ];
    # # };
    # "chardet" = super.buildPythonPackage rec {
    #   pname = "chardet";
    #   version = "3.0.4";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl";
    #     sha256 = "14b621614q2lw7ik2igdv4qdbblqgdsiglgl5fhf1l5fmvy3ycpw";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [ ];
    # };
    # # "cryptography" = super.buildPythonPackage rec {
    # #   pname = "cryptography";
    # #   version = "3.4.4";
    # #   src = fetchurl {
    # #     url = "https://files.pythonhosted.org/packages/27/5a/007acee0243186123a55423d49cbb5c15cb02d76dd1b6a27659a894b13a2/cryptography-3.4.4.tar.gz";
    # #     sha256 = "0j680r1453r1ws6hnpfns80kh82xlry7ihhmmgdvnvvbhpq1jppf";
    # #   };
    # #   format = "setuptools";
    # #   doCheck = false;
    # #   buildInputs = [ ];
    # #   checkInputs = [ ];
    # #   nativeBuildInputs = [ ];
    # #   propagatedBuildInputs = [
    # #     self."cffi"
    # #   ];
    # # };
    # "idna" = super.buildPythonPackage rec {
    #   pname = "idna";
    #   version = "2.10";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl";
    #     sha256 = "1h280sli58v5dapmf79rnnqdrrk0xjn8vi3pxppknllv3r5q0zdr";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [ ];
    # };
    # "prettytable" = super.buildPythonPackage rec {
    #   pname = "prettytable";
    #   version = "2.0.0";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/94/d5/52e48f3bcf66f838d411ad85c3ac9550c2451d082623e2d4d4df7411ed5c/prettytable-2.0.0-py3-none-any.whl";
    #     sha256 = "1f9yvw5g4qv70sxlndfbdwc1mhxqszlqm5c6rpm8vx17langrisx";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [
    #     self."setuptools"
    #     self."wcwidth"
    #   ];
    # };
    # "pycparser" = super.buildPythonPackage rec {
    #   pname = "pycparser";
    #   version = "2.20";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl";
    #     sha256 = "01apwc8fj6qh7lr01yxmns475rfhz07gccr8220ws3wgcwiav0km";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [ ];
    # };
    # # "pycryptodomex" = super.buildPythonPackage rec {
    # #   pname = "pycryptodomex";
    # #   version = "3.10.1";
    # #   src = fetchurl {
    # #     url = "https://files.pythonhosted.org/packages/82/e2/a0f9f5452a59bafaa3420585f22b58a8566c4717a88c139af2276bb5695d/pycryptodomex-3.10.1.tar.gz";
    # #     sha256 = "0qix4q55sq27r5a9jkgynw136j2kidwhnhlgnjkikysjwbix672l";
    # #   };
    # #   format = "setuptools";
    # #   doCheck = false;
    # #   buildInputs = [];
    # #   checkInputs = [];
    # #   nativeBuildInputs = [];
    # #   propagatedBuildInputs = [];
    # # };
    "pynacl" = super.buildPythonPackage rec {
      pname = "pynacl";
      version = "1.4.0";
      src = fetchurl {
        url = "https://files.pythonhosted.org/packages/cf/5a/25aeb636baeceab15c8e57e66b8aa930c011ec1c035f284170cacb05025e/PyNaCl-1.4.0.tar.gz";
        sha256 = "01b56hxrbif3hx8l6rwz5kljrgvlbj7shmmd2rjh0hn7974a5sal";
      };
      format = "setuptools";
      doCheck = false;
      buildInputs = [ ];
      checkInputs = [ ];
      nativeBuildInputs = [ ];
      propagatedBuildInputs = [
        self."cffi"
        self."six"
      ];
    };
    # "requests" = super.buildPythonPackage rec {
    #   pname = "requests";
    #   version = "2.24.0";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl";
    #     sha256 = "165qrd22rm0fp23kzfdc6qy12jv0fm7j4jbhzi394fs4m6acqxgy";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [
    #     self."certifi"
    #     self."chardet"
    #     self."idna"
    #     self."urllib3"
    #   ];
    # };
    # "six" = super.buildPythonPackage rec {
    #   pname = "six";
    #   version = "1.15.0";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl";
    #     sha256 = "1vaw9aqdsbg84s20yqmg24k5kcq65dpxg4bldpzkijmspgfbwx4b";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [ ];
    # };
    # "toml" = super.buildPythonPackage rec {
    #   pname = "toml";
    #   version = "0.10.2";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl";
    #     sha256 = "16sgpg57kxx5jh467d9qwc2hwshfvdbl0xkafdp3qspvbfp46qc0";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [ ];
    # };
    # "urllib3" = super.buildPythonPackage rec {
    #   pname = "urllib3";
    #   version = "1.25.11";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl";
    #     sha256 = "0pnxjyc33d162wrxmk285av9x44h9sqpzzhbzl7gmzpk9fz1ycpm";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [ ];
    # };
    # "wcwidth" = super.buildPythonPackage rec {
    #   pname = "wcwidth";
    #   version = "0.2.5";
    #   src = fetchurl {
    #     url = "https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl";
    #     sha256 = "1177pfa343r378020a85l3b16ak479qgyvh8k5719fgbkhm81d5y";
    #   };
    #   format = "wheel";
    #   doCheck = false;
    #   buildInputs = [ ];
    #   checkInputs = [ ];
    #   nativeBuildInputs = [ ];
    #   propagatedBuildInputs = [ ];
    # };
  };
}
